name: Simple CI/CD Demo

on:
  push:
    branches:
      - staging   # auto deploy when staging branch updates
  workflow_dispatch: # manual trigger for dev and main

jobs:
  deploy:
    runs-on: self-hosted   # Windows server runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to IIS (Simple Copy)
        shell: pwsh
        run: |
          $branch = "${{ github.ref_name }}"
          
          if ($branch -eq "staging") {
            $dest = "C:\inetpub\wwwroot\simple-staging"
          } elseif ($branch -eq "dev") {
            $dest = "C:\inetpub\wwwroot\simple-dev"
          } elseif ($branch -eq "main") {
            $dest = "C:\inetpub\wwwroot\simple-prod"
          } else {
            Write-Host "Branch not configured for deployment."
            exit 0
          }

          if (!(Test-Path $dest)) { New-Item -ItemType Directory -Path $dest | Out-Null }

          Remove-Item -Recurse -Force "$dest\*" -ErrorAction SilentlyContinue
          Copy-Item -Recurse -Force "${{ github.workspace }}\*" $dest

          Write-Host "✅ Deployed $branch branch to $dest"
